---

ocp4_workload_integreatly_user_count: 50
ocp4_workload_integreatly_user_password: "{{ lookup('password', '/tmp/intly-userpass length=16 chars=ascii_letters,digits') }}"
ocp4_workload_integreatly_dedicated_admin_user_password: "{{ lookup('password', '/tmp/intly-dauserpass length=16 chars=ascii_letters,digits') }}"
ocp4_workload_integreatly_admin_user_password: "{{ lookup('password', '/tmp/intly-adminpass length=16 chars=ascii_letters,digits') }}"

# override ocp workloads to include prerequisite roles
ocp_workloads:
  - ocp4_workload_integreatly_minio
  - ocp4-workload-authentication
  - ocp4_workload_integreatly

ocp4_workload_authentication_vars:
  idm_type: htpasswd
  
  htpasswd_user_base: evals
  htpasswd_user_password: "{{ ocp4_workload_integreatly_user_password }}"
  htpasswd_user_count: "{{ ocp4_workload_integreatly_user_count | int }}"

  # This user is not available in RHMI production/poc clusters. Only RHMI operations teams have cluster-admin access
  admin_user: admin
  htpasswd_admin_password: "{{ ocp4_workload_integreatly_admin_user_password }}"
