---

# The number of users that should be set up in the IDP
# The number of RHMI per-user 3scale tenants created in the cluster
# The number of RHMI per-user Fuse Online instances in the cluster
ocp4_workload_integreatly_user_count: 50

# Base name of users in the cluster, users will be created with the format:
# {ocp4_workload_integreatly_user_base}{0...ocp4_workload_integreatly_user_count}
ocp4_workload_integreatly_user_base: evals

# A note on lookup('password', ...)
# This will create a file with a generated password
# If the file already exists, the contents of the file will be used

# Password for rhmi-developers (not cluster admin, not dedicated admin) RHMI users
ocp4_workload_integreatly_user_password: "{{ lookup('password', '/tmp/intly-userpass length=16 chars=ascii_letters,digits') }}"
# Password for dedicated-admin RHMI users
ocp4_workload_integreatly_dedicated_admin_user_password: "{{ lookup('password', '/tmp/intly-dauserpass length=16 chars=ascii_letters,digits') }}"
# Password for cluster admin users
ocp4_workload_integreatly_admin_user_password: "{{ lookup('password', '/tmp/intly-adminpass length=16 chars=ascii_letters,digits') }}"

# Overrides for OCP workloads to include prerequisite roles
ocp_workloads:
  - ocp4_workload_integreatly_minio
  - ocp4-workload-authentication
  - ocp4_workload_integreatly

# Overrides for authentication prerequisite role
ocp4_workload_authentication_vars:
  idm_type: htpasswd
  
  # Ensure the htpasswd IDP users use the same base as the RHMI roles
  htpasswd_user_base: "{{ ocp4_workload_integreatly_user_base }}"
  # Ensure the htpasswd IDP users match with the RHMI roles
  htpasswd_user_password: "{{ ocp4_workload_integreatly_user_password }}"
  # Ensure the htpasswd user count matches with the RHMI roles
  htpasswd_user_count: "{{ ocp4_workload_integreatly_user_count | int }}"

  # This user is not available in RHMI production/poc clusters. Only RHMI operations teams have cluster-admin access
  admin_user: admin
  htpasswd_admin_password: "{{ ocp4_workload_integreatly_admin_user_password }}"
