---

ocp4_workload_integreatly_user_count: 50

# override ocp workloads to include prerequisite roles
ocp_workloads:
  - ocp4-workload-integreatly-minio
  - ocp4-workload-authentication
  - ocp4-workload-integreatly

ocp4_workload_authentication_vars:
  idm_type: htpasswd
  
  htpasswd_user_base: evals
  htpasswd_user_count: "{{ ocp4_workload_integreatly_user_count | int }}"

  # This user is not available in RHMI production/poc clusters. Only RHMI operations teams have cluster-admin access
  admin_user: admin
