---
- name: Get OAuth URL
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    name: oauth-openshift
    namespace: openshift-authentication
  register: _action_get_oauth_route

- name: Get RHMI Cluster SSO URL
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    name: keycloak-edge
    namespace: redhat-rhmi-rhsso
  register: _action_get_cluster_sso_route

- name: Set facts for SSO IDP
  set_fact:
    ocp4_workload_integreatly_sso_idp_oauth_url: "https://{{ _action_get_oauth_route.resources[0].spec.host }}"

- name: Create expected resources
  k8s:
    state: present
    namespace: redhat-rhmi-rhsso
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item) | from_yaml }}"    
  retries: 3
  delay: 5
  register: _create_resources
  until: _create_resources is succeeded
  loop:
  - keycloakrealm-idp.yml.j2


- name: Create SSO OAuth Secret
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: openshift
        namespace: openshift-config
      data:
        clientSecret: "{{ 'openshift' | b64encode }}"
      type: Opaque

- name: Add SSO IDP to the OpenShift cluster
  shell: "oc patch oauth cluster --type=json -p '[{\"op\":\"add\", \"path\":\"/spec/identityProviders/-\", \"value\":{ \"name\": \"'{{ ocp4_workload_integreatly_sso_idp_realm_name }}'\", \"mappingMethod\": \"claim\", \"type\": \"OpenID\", \"openID\": { \"ca\": {\"name\": \"''\"}, \"clientID\": \"{{ ocp4_workload_integreatly_sso_idp_realm_name }}-client\", \"clientSecret\": { \"name\": \"'{{ ocp4_workload_integreatly_sso_idp_client_secret }}'\" }, \"issuer\": \"'https://{{ _action_get_cluster_sso_route.resources[0].spec.host }}'/auth/realms/'{{ ocp4_workload_integreatly_sso_idp_realm_name }}'\", \"claims\": { \"preferredUsername\": [\"preferred_username\"], \"email\": [\"email\"], \"name\": [\"name\"] } } } }]'"